pipeline {
    agent any

    tools {
        maven 'Maven 3.9.6' // Adjust version as per your Jenkins configuration
        jdk 'JDK 21'        // Adjust version as per your Jenkins configuration
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('backend') {
                    sh 'chmod +x mvnw'
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Test') {
            steps {
                dir('backend') {
                    sh './mvnw test'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('backend') {
                    script {
                        docker.build("rhine-backend:${env.BUILD_ID}")
                    }
                }
            }
        }
    }
}
