pipeline {
    agent any

    environment {
        DOCKER_REGISTRY_CREDENTIALS = 'docker-token' 
        DOCKER_REGISTRY = 'onantabee' 
        KUBECONFIG_CREDENTIALS = 'kubeconfig'
        DOCKER_HOST= 'unix:///var/run/docker.sock'
    }

    tools {
        nodejs 'NodeJS 20'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Parallel Build & Push') {
            parallel {
                stage('Frontend') {
                    stages {
                        stage('Install Dependencies') {
                            steps {
                                dir('frontend') {
                                    sh 'npm ci'
                                }
                            }
                        }
                        stage('Lint & Test (Frontend)') {
                            steps {
                                dir('frontend') {
                                    // sh 'npm run lint' 
                                    echo "Skipping Linting for now to proceed with deployment"
                                }
                            }
                        }
                        stage('Build (Frontend)') {
                            steps {
                                dir('frontend') {
                                    sh 'npm run build'
                                }
                            }
                        }
                        stage('Docker Build & Push (Frontend)') {
                            steps {
                                dir('frontend') {
                                    script {
                                        withCredentials([usernamePassword(credentialsId: env.DOCKER_REGISTRY_CREDENTIALS, usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWORD')]) {
                                            sh '''
                                                export DOCKER_CONFIG=$(pwd)/.docker_jenkins
                                                mkdir -p $DOCKER_CONFIG

                                                AUTH=$(printf "${DOCKER_USER}:${DOCKER_PASSWORD}" | base64)

                                                echo "{\\"auths\\": {\\"https://index.docker.io/v1/\\": {\\"auth\\": \\"${AUTH}\\"}}}" > $DOCKER_CONFIG/config.json
                                                
                                                docker build -t $DOCKER_REGISTRY/rhine-frontend:$BUILD_ID .
                                                
                                                # Retry push 3 times to beat the 400 Bad Request
                                                (docker push $DOCKER_REGISTRY/rhine-frontend:$BUILD_ID || \
                                                 sleep 5 && docker push $DOCKER_REGISTRY/rhine-frontend:$BUILD_ID || \
                                                 sleep 10 && docker push $DOCKER_REGISTRY/rhine-frontend:$BUILD_ID)

                                                docker push $DOCKER_REGISTRY/rhine-frontend:latest
                                                
                                                rm -rf $DOCKER_CONFIG
                                            '''
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

                stage('Backend') {
                    stages {
                        stage('Build (Backend)') {
                            steps {
                                dir('backend') {
                                    sh 'chmod +x mvnw'
                                    sh './mvnw clean package -DskipTests'
                                }
                            }
                        }
                        stage('Test (Backend)') {
                            steps {
                                dir('backend') {
                                    sh './mvnw test'
                                }
                            }
                        }
                        stage('Docker Build & Push (Backend)') {
                            steps {
                                dir('backend') {
                                    script {
                                        withCredentials([usernamePassword(credentialsId: env.DOCKER_REGISTRY_CREDENTIALS, usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWORD')]) {
                                            sh '''
                                                export DOCKER_CONFIG=$(pwd)/.docker_jenkins
                                                mkdir -p $DOCKER_CONFIG

                                                AUTH=$(printf "${DOCKER_USER}:${DOCKER_PASSWORD}" | base64)

                                                echo "{\\"auths\\": {\\"https://index.docker.io/v1/\\": {\\"auth\\": \\"${AUTH}\\"}}}" > $DOCKER_CONFIG/config.json
                                                
                                                docker build -t $DOCKER_REGISTRY/rhine-backend:$BUILD_ID .
                                                
                                                # Retry push 3 times to beat the 400 Bad Request
                                                (docker push $DOCKER_REGISTRY/rhine-backend:$BUILD_ID || \
                                                 sleep 5 && docker push $DOCKER_REGISTRY/rhine-backend:$BUILD_ID || \
                                                 sleep 10 && docker push $DOCKER_REGISTRY/rhine-backend:$BUILD_ID)

                                                docker push $DOCKER_REGISTRY/rhine-backend:latest
                                                
                                                rm -rf $DOCKER_CONFIG
                                            '''
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        stage('Deploy Backend & DB') {
            steps {
                script {
                    withCredentials([file(credentialsId: env.KUBECONFIG_CREDENTIALS, variable: 'KUBECONFIG')]) {
                        sh "sed -i 's|\${DOCKER_REGISTRY}|${env.DOCKER_REGISTRY}|g' ops/k8s/backend-deployment.yaml"
                        sh "sed -i 's|\${BUILD_ID}|${env.BUILD_ID}|g' ops/k8s/backend-deployment.yaml"
                        
                        // Check if secret exists, if not create it automatically
                        sh """
                            if kubectl get secret mysql-secret > /dev/null 2>&1; then
                                echo "***************************************************************** + mysql-secret already exists + *****************************************************************"
                            else
                                echo "***************************************************************** + Creating mysql-secret with default credentials + *****************************************************************"
                                kubectl create secret generic mysql-secret \\
                                  --from-literal=mysql-root-password=Shangrilla#123 \\
                                  --from-literal=mysql-database=taskdb \\
                                  --from-literal=mysql-user=root \\
                                  --from-literal=mysql-password=Shangrilla#123
                            fi
                        """ 
                        sh 'kubectl apply -f ops/k8s/mysql-pvc.yaml'
                        sh 'kubectl apply -f ops/k8s/mysql-deployment.yaml'
                        
                        sh 'kubectl apply -f ops/k8s/backend-deployment.yaml'
                    }
                }
            }
        }

        stage('Deploy Frontend') {
            steps {
                script {
                    withCredentials([file(credentialsId: env.KUBECONFIG_CREDENTIALS, variable: 'KUBECONFIG')]) {
                        def backendIp = ""
                        timeout(time: 5, unit: 'MINUTES') {
                            waitUntil {
                                script {
                                    def host = sh(script: "kubectl get svc rhine-backend-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'", returnStdout: true).trim()
                                    
                                    if (host == "") {
                                        host = sh(script: "kubectl get svc rhine-backend-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}'", returnStdout: true).trim()
                                    }

                                    if (host != "") {
                                        backendIp = (host == "localhost") ? "host.docker.internal" : host
                                        return true
                                    }
                                    return false
                                }
                            }
                        }
                        
                        echo "Backend IP detected: ${backendIp}"
                        
                        sh "sed -i 's|\${DOCKER_REGISTRY}|${env.DOCKER_REGISTRY}|g' ops/k8s/frontend-deployment.yaml"
                        sh "sed -i 's|\${BUILD_ID}|${env.BUILD_ID}|g' ops/k8s/frontend-deployment.yaml"
                        sh "sed -i 's|REPLACE_WITH_REAL_IP|http://${backendIp}:8080|g' ops/k8s/frontend-deployment.yaml"
                        
                        sh 'kubectl apply -f ops/k8s/frontend-deployment.yaml'
                        
                        sh 'kubectl get pods'
                        sh 'kubectl get services'
                    }
                }
            }
        }

    }
}

